version: '3'


services:
  
  backend:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:6-jammy
    restart: always
    ports:
      - '27017:27017'
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s